### ISSUE TITLE
Add "Documentation" dropdown to Navbar

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/web-components#100]
### Feature description

We need to update the main navigation bar (aka _Navbar_) to replace the current "Documentation" link with a "Documentation" dropdown that shows various links to documentation pages.

We could try and use the ["Masthead" Carbon for IBM.com](https://www.ibm.com/standards/carbon/components/masthead) component if possible, or maybe at least take some inspiration from its implementation.

### Dependencies

This issue depends on:

- https://github.com/Qiskit/saiba/issues/134

### Ressources

- Design: https://www.figma.com/file/xc1jekL6jga6NyRH64k1mV/documentation-redesign?node-id=136%3A1821
- Prototype: https://www.figma.com/proto/xc1jekL6jga6NyRH64k1mV/documentation-redesign?page-id=152%3A1426&node-id=179%3A1819&viewport=335%2C-122%2C0.34&scaling=min-zoom&starting-point-node-id=179%3A1819&show-proto-sidebar=1

### Design capture

![Screenshot 2022-08-24 at 10 51 30](https://user-images.githubusercontent.com/22047320/186374822-e527c96d-2f26-4fa3-9691-daa9c6c8c785.png)

### Additional context

- Please reach out to @JRussellHuffman for any questions on the design.
- _Carbon for IBM.com_'s _Masthead_ web component: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/tree/main/packages/web-components/src/components/masthead

**Comment by techtolentino** [comment]
Tracking dependency issue with the Carbon for IBM dotcom web-components package, [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/8927).

**Comment by y4izus** [comment]
Hey @abdonrd and @techtolentino !! I've started working on this issue :)

**Comment by abdonrd** [comment]
I have also created:
- This issue: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9044
- This PR: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/9045

**Comment by abdonrd** [comment]
We have had another problem regarding the extensions, but it has been solved!

- Issue: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9069
- PR: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/9089

**Comment by abdonrd** [comment]
I just found a temporally solution using the `overrides` field!
- https://github.com/Qiskit/web-components/pull/129

**Comment by eddybrando** [comment]
> Hi can someone update me on the status of this? Has the carbon fix been released yet and is this issue still being worked on?

We're now unblocked and the issue is part of the priorities for this sprint. 🙂

**Comment by yoshiemuranaka** [comment]
When trying to import the masthead component, seeing this error in the browser and the component does not render.

```js
Uncaught SyntaxError: The requested module './../../../../../../../redux-logger/dist/redux-logger.js' does not provide an export named 'createLogger' (at store.ts:13:10)
```

The button group component seemed to work as documented, but many others (including masthead) do not work when imported as documented https://github.com/carbon-design-system/carbon-for-ibm-dotcom/tree/main/packages/web-components#webpack-application-setup

WIP branch https://github.com/Qiskit/web-components/tree/feat/doc-100

**Comment by abdonrd** [comment]
Looks like the error is because the masthead component uses some CommonJS packages (like the `redux-logger`).

I just quick tried adding the `@rollup/plugin-commonjs`, but I haven't been able to get it to resolve it.

**Comment by eddybrando** [comment]
After many internal discussions, we realise that the `Masthead` component from the **Carbon for IBM.com** library, sadly, isn't customisable enough for our use case.

Our design is based on the Carbon design system and extends the Carbon components library. **Carbon for IBM.com** does the same but goes on another direction, very specific of the needs of the IBM.com marketing pages and their design specifications.

We've decided to extend our current `Navbar` web component and attempt to add a mega menu similar to the one implemented in their `Masthead` component, still making good use of their implementation as a reference.

**Comment by JRussellHuffman** [comment]
Is there an example or two of what is natively supported? And is it worth redesigning things to more closely match what is supported?

**Comment by yoshiemuranaka** [comment]
> Is there an example or two of what is natively supported? And is it worth redesigning things to more closely match what is supported?

We should be able to use any of the carbon web-components, but not seeing anything that would work for this design
https://web-components.carbondesignsystem.com/?path=/story/introduction-form-participation--page
https://carbondesignsystem.com/developing/frameworks/web-components

Our current nav bar implementation is a mix of custom HTML/JS and the carbon Dropdown web-component. 
Today, I started exploring whether or not we could use the [UIShell component ](https://web-components.carbondesignsystem.com/?path=/story/components-ui-shell--header)–but this doesn't necessarily solve the need for a custom (mega)dropdown for the Documentation nav item. I started the exploration because the ibmdotcom masthead uses it as a base. 

Hope that helps.

**Comment by yoshiemuranaka** [comment]
@JRussellHuffman is there a design for the mobile mega menu?

**Comment by JRussellHuffman** [comment]
yes, [here](https://www.figma.com/file/xc1jekL6jga6NyRH64k1mV/documentation-redesign?node-id=179%3A1819), although it may be easiest to view through the [prototype view](https://www.figma.com/proto/xc1jekL6jga6NyRH64k1mV/documentation-redesign?page-id=152%3A1426&node-id=171%3A1903&viewport=637%2C138%2C0.11&scaling=min-zoom&starting-point-node-id=179%3A1819&show-proto-sidebar=1). I tried to follow the carbon masthead pretty closely.

**Comment by techtolentino** [comment]
Dropping in some screen captures until @yoshiemuranaka gets access to Figma

**mobile**
![Screen Shot 2022-09-06 at 11 29 02 AM](https://user-images.githubusercontent.com/6276074/188712746-730f996e-7389-444e-8588-e848a622a5f9.png)


**prototype of Medium and Small viewports**

https://user-images.githubusercontent.com/6276074/188712878-c50a6a5f-f171-4521-80a7-9c498ba30a6d.mov

**Comment by javabster** [comment]
Hi folks, I left a comment in the user story issue but not sure if anyone has seen it so just reposting here: https://github.com/Qiskit/qiskit.org/issues/2702#issuecomment-1225894054

**Comment by yoshiemuranaka** [comment]
> Hi folks, I left a comment in the user story issue but not sure if anyone has seen it so just reposting here: [Qiskit/qiskit.org#2702 (comment)](https://github.com/Qiskit/qiskit.org/issues/2702#issuecomment-1225894054)

Hi @javabster posted a response here https://github.com/Qiskit/web-components/pull/140#issuecomment-1239430472
