### ISSUE TITLE
[Navbar UI] Transparent background

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/web-components#137]
### Steps to reproduce the problem

1. visit any saiba page that has enough content to warrant a vertical scroll 
2. see error

### What is the current behavior?

the main site nav has a transparent background, allowing content to be visible through the nav

### What is the expected behavior?

the main site nav should have a defined `background-color`

### Additional information

Originally reported by @techtolentino in https://github.com/Qiskit/saiba/issues/120

### Screenshots

https://user-images.githubusercontent.com/6276074/186512267-4ac90363-4ced-4d57-8940-7f235b55bd40.mov

**Comment by yoshiemuranaka** [comment]
Should be fixed when we update saiba with new UI shell https://github.com/Qiskit/saiba/issues/107
