### ISSUE TITLE
[UI Shell] - need to differentiate Overview CTA from Documentation > Overview CTA

### ISSUE THREAD

**Issue by yoshiemuranaka** [Qiskit/web-components#161]
### Steps to reproduce the problem

On qiskit.org make sure to have the segment extension. First click the top navigation `Overview` link. Then click `Documentation` and click `Overview` from the dropdown. See in segment that both events have the same CTA

### What is the current behavior?

Currently, we have the segment click event CTA value as the navbar link label. This is an issue specifically for the `Overview` in the top-level nav and the `Documentation > Overview` in the documentation dropdown

### What is the expected behavior?

Should be able to differentiate different each link clicked in ui-shell

### Screenshots

<img width="1676" alt="Screen Shot 2022-09-19 at 10 14 50 AM" src="https://user-images.githubusercontent.com/8097306/191075031-d9d6c86a-1828-478c-a27a-10936cd52234.png">

### Additional information

Consider adding parent menu label as prefix for all nested links

**Comment by eddybrando** [comment]
FYI @agebbie
