### ISSUE TITLE
Bug: Overview link in documentation dropdown doesn't direct to overview

### ISSUE THREAD

**Issue by javabster** [Qiskit/web-components#193]
### Steps to reproduce the problem

1. go to qiskit.org
2. click on documentation in the top menu
3. when the documentation menu expands, go to the left, click the "overview" link under getting started
4. this link directs users to the "getting started" page rather than the overview page

### What is the current behavior?

the overview link directs users to the getting started page in the qiskit documentation

### What is the expected behavior?

the overview link should go to the the overview page of the qiskit documentation (https://qiskit.org/documentation/index.html)

I think it would also be good if we could add a heading in that section specifically directing users to the getting started page

**Comment by HuangJunye** [comment]
<img width="147" alt="image" src="https://user-images.githubusercontent.com/7631333/213416029-c86829b6-6bb0-4ad1-bd2e-a5ef6eb9d6c1.png">

I agree that "Overview" linking to "Getting started" page is confusing, but I think the heading "Getting Started" here is also confusing. Maybe we should change to 

**Start Here**
Overview (link to https://qiskit.org/documentation/index.html)
Getting started (link to https://qiskit.org/documentation/getting_started.html)

**Comment by javabster** [comment]
I like that suggestion! I think it's important to have both the overview link and the getting started link somewhere in the top menu.

**Comment by javabster** [comment]
I would also be open to changing the word "Overview" to "Documentation Home", but that might require more alignment with the Qiskit teams to rename that page in their docs build 🤔

**Comment by HuangJunye** [comment]
> I would also be open to changing the word "Overview" to "Documentation Home", but that might require more alignment with the Qiskit teams to rename that page in their docs build 🤔

I have the same thought while reading https://github.com/Qiskit/web-components/issues/194. Maybe we should keep the overview page on the website as is and change the "Overview" on the documentation page to "Documentation Home".

Prior to https://github.com/Qiskit/qiskit/pull/1631 (for example, https://qiskit.org/documentation/stable/0.39/index.html), "Overview" page on doc was called "Documentation Homepage" so I don't think the Qiskit maintainers would have issues changing it to "Documentation Home".
