### ISSUE TITLE
Multiple "Overview" buttons on top menu causes confusion for documentation users

### ISSUE THREAD

**Issue by javabster** [Qiskit/web-components#194]
In the qiskit.org top menu there are 2 instances of the word "Overview". One at the top level and one inside the documentation dropdown. This was recently raised by a Qiskit maintainer as confusing for documentation users because when users go to the documentation page there is an overview page and it isn't clear that the top menu "Overview" redirects back to the qiskit.org homepage instead of the documentation overview page. I suggest renaming the top level "Overview" to "Home" as a way to prevent this confusion.

![topmenu](https://user-images.githubusercontent.com/23662430/213245459-ebdba8db-f77b-4b6a-9b8f-7fdb0a3096e4.png)

**Comment by javabster** [comment]
A more detailed example, lets say I am a documentation user, I am looking at the "Getting Started" page of the documentation, I would see the following page view:

![docs](https://user-images.githubusercontent.com/23662430/213418570-cca74a00-26bb-4327-be06-8f7e15f438ac.png)
 
but if I want to go back to the documentation "Overview" page I might assume I could get there by clicking the top bar "Overview" button, but actually i need to click the left hand sidebar "Overview" button

**Comment by techtolentino** [comment]
This issue could've potentially been solved by https://github.com/Qiskit/web-components/pull/197

@javabster @HuangJunye - do you agree?

**Comment by javabster** [comment]
yep I think so, and the "overview" in the top menu is going to be removed at some point in the near future anyway, so i think we are good to close this issue :)

**Comment by techtolentino** [comment]
Closed by https://github.com/Qiskit/web-components/pull/197

Thank you team!
