### ISSUE TITLE
[UI-Shell] update navigation items

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/web-components#204]
### Feature description

- related to [this issue in the Qiskit.org repo](https://github.com/Qiskit/qiskit.org/issues/2855)
  - specifically [this comment](https://github.com/Qiskit/qiskit.org/issues/2855#issuecomment-1419363797)
- also related to https://github.com/Qiskit/web-components/issues/160

Main menu updates:
- [x] The link to the `Providers` page will be near the `Documentation` link, on the right side
- [ ] ~~The links to `Providers` and `Core` will be removed from the Documentation drop-down menu.~~ Not yet

### Additional context

Here we need to decide if the block will continue having the size of the screen or if we want that block to adjust to the content on the submenu. **Update**: We don't need to remove the providers and core section from the menu, so the size will remain the same

Note: possibly related is this issue from @HuangJunye, regarding the _width_ and usability of the UI Shell Documentation dropdown

**Comment by HuangJunye** [comment]
Thanks for the ping @techtolentino. Did you want to link https://github.com/Qiskit/web-components/issues/160 to the description?
