### ISSUE TITLE
Linter import error

### ISSUE THREAD

**Issue by mentesniker** [Qiskit/web-components#71]
Hi, so when running npm run lint in #67 we have the following error:
![image](https://user-images.githubusercontent.com/35209340/165675759-3f861171-2dbb-4797-8d12-4382649a3a66.png)
However if we look inside lit standar docs, we can see that [TemplateResult is indeed inside lit...](https://lit.dev/docs/api/templates/#TemplateResult)

**Comment by abdonrd** [comment]
Oh! The error could be better...
The problem there is that `TemplateResult` is a type.

Replace:
```typescript
import { LitElement, html, TemplateResult } from 'lit';
```

With:
```typescript
import { LitElement, html, type TemplateResult } from 'lit';
```

**Comment by mentesniker** [comment]
Yes you were rigth, I'm closing this issue as the problem was solved.
